// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ordering.StateService;

namespace Ordering.StateService.Migrations
{
    [DbContext(typeof(BurgerOrderStateDbContext))]
    [Migration("20210121002113_AddOrderIdConstraints2")]
    partial class AddOrderIdConstraints2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TooBigToFailBurgerShop.Ordering.State.BurgerOrderStateInstance", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BurgerOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CorrelationId");

                    b.ToTable("BurgerOrderStateInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
