apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: create-order-subscription
spec:
  topic: TooBigToFailBurgerShop.Ordering.Contracts:SubmitBurgerOrder
  route: /TooBigToFailBurgerShop.Ordering.Contracts%3ASubmitBurgerOrder
  pubsubname: burgers-pubsub
scopes:
- burgers.ordering.api
- burgers.create.order.consumer