version: '3.4'

services:

  burgers.webspa:
    image: burgers.webspa
    build:
      context: .
      dockerfile: web/Burgers.WebSPA/Dockerfile

  burgers.ordering.api:
    image: burgers.ordering.api
    build:
      context: .
      dockerfile: services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - "burgers.data"

  burgers.data:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "burger"
      POSTGRES_PASSWORD: "burger"
      POSTGRES_DB: "burgers"

  burgers.create.order.consumer:
    image: burgers.create.order.consumer
    build:
      context: .
      dockerfile: services/Ordering/CreateOrder.Consumer/Dockerfile

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  ordering.stateservice:
    image: ordering.stateservice
    build:
      context: .
      dockerfile: services/Ordering/Ordering.StateService/Ordering.StateService/Dockerfile

