version: '3.4'

services:
  burgers.ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6969:80"

  burgers.data:
    volumes:
      - burgers_data_db_volume:/var/lib/postgresql/data

  burgers.create.order.consumer:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  burgers.webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6968:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  burgers.ordering.state.service:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  burgers.process.order.consumer:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

volumes:
  burgers_data_db_volume: